Repository taylorwilsdon/google_workspace_mcp, pull requests merged in 2025-08, with the labels that each got.

#142 Fix Google Slides getThumbnail API parameter names
  gslides/slides_tools.py
Labels: bug

#150 centralize redirect uri logic and update GOOGLE_OAUTH_REDIRECT_URI docs
  README.md
  auth/oauth_callback_server.py
  auth/oauth_common_handlers.py
  core/config.py
Labels: bug, documentation, enhancement

#153 feat: Streamlined VSCode OAuth Support
  README.md
  auth/google_remote_auth_provider.py
  auth/oauth21_integration.py
  auth/oauth_callback_server.py
  auth/oauth_common_handlers.py
  auth/oauth_config.py
  auth/oauth_error_handling.py
  auth/oauth_types.py
  auth/service_decorator.py
  core/config.py
  core/server.py
  install_claude.py
  main.py
  uv.lock
Labels: enhancement

#156 fix: handle JSON string input for modify_sheet_values parameter
  gsheets/sheets_tools.py
Labels: bug

#159 feat: Enhanced Google Doc Editing Granularity
  .gitignore
  README.md
  gdocs/docs_helpers.py
  gdocs/docs_structure.py
  gdocs/docs_tables.py
  gdocs/docs_tools.py
  gdocs/managers/__init__.py
  gdocs/managers/batch_operation_manager.py
  gdocs/managers/header_footer_manager.py
  gdocs/managers/table_operation_manager.py
  gdocs/managers/validation_manager.py
  uv.lock
Labels: enhancement

#166 enh: Cleanup & Consolidate OAuth Logic
  .github/workflows/ruff.yml
  auth/oauth_common_handlers.py
  auth/oauth_config.py
  auth/service_decorator.py
  core/server.py
  gdocs/docs_tables.py
  gdocs/docs_tools.py
  gdocs/managers/table_operation_manager.py
  gdocs/managers/validation_manager.py
Labels: enhancement

#164 remove user_google_email parameter for multi-user mode
  README.md
  auth/service_decorator.py
  gdocs/docs_tools.py
  main.py
Labels: enhancement

#173 feat: enhance Google Docs and Drive functionality with image insertion and permission checking
  core/tool_tiers.yaml
  core/utils.py
  gdocs/docs_helpers.py
  gdrive/drive_helpers.py
  gdrive/drive_tools.py
  uv.lock
Labels: enhancement

#184 enh: Safe logging & Log Formatting
  core/log_formatter.py
  gtasks/tasks_tools.py
  main.py
  pyproject.toml
  uv.lock
Labels: enhancement
